repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.4
  hooks:
  -   id: trailing-whitespace
  -   id: end-of-file-fixer
- repo: git://github.com/pre-commit/mirrors-eslint
  sha: v4.1.1
  hooks:
  - id: eslint
    additional_dependencies: [
      'eslint',
      'babel-eslint',
      'eslint-plugin-babel',
      'eslint-plugin-react',
      'eslint-plugin-promise',
      'eslint-plugin-prefer-object-spread',
      'eslint-plugin-no-loops',
      'eslint-plugin-sort-imports-es6-autofix'
    ]
    args: [--quiet]
- repo: git://github.com/lfhbento/mirrors-prettier-eslint-cli
  sha: 2b0f6f85118b95ec3b22e49387e5136410eb7c57
  hooks:
  -   id: prettier-eslint
