-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 4c90c9557da7c0d695d6a729bae8b1de4e496cbf
    hooks:
    -   id: trailing-whitespace
-   repo: git://github.com/pre-commit/mirrors-eslint
    sha: v3.7.0
    hooks:
    -   id: eslint
        additional_dependencies: ['babel-eslint@7.0.0', 'eslint-plugin-react@6.4.1']
-   repo: git://github.com/pre-commit/mirrors-fixmyjs
    sha: a85f43b8e3ccc30438770cc0b1c4f9809a10afb4
    hooks:
    -   id: fixmyjs
        args:
        - -l
        - -c
        - .jshintrc
        exclude: (config\/js\/slate.*|config\/v1.*)
